services:
  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  web:
    build: .
    volumes:
      - "./uploads/:/code/uploads"
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
