apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\danil\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: thumbnails-service
  name: thumbnails-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thumbnails-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\danil\AppData\Local\Microsoft\WinGet\Links\kompose.exe convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: thumbnails-service
    spec:
      containers:
        - image: thumbnails-service
          imagePullPolicy: Never
          name: thumbnails-service
          volumeMounts:
            - mountPath: /code/uploads
              name: upload
      restartPolicy: Always
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: upload
